// <auto-generated />
namespace E02_EF6_PublishingCompany_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _01_genre_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_genre_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202407031747101_01_genre_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
