// <auto-generated />
namespace E02_EF6_PublishingCompany_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _04_addGenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04_addGenres));
        
        string IMigrationMetadata.Id
        {
            get { return "202407131757471_04_addGenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
